### ISSUE TITLE
Error on loading.

### ISSUE THREAD

**Issue by TheBitcoinBaron** [Leonm99/Stable-Diffusion-Video2Video#4]
When loading up after adding the script, this error message appears:  

Traceback (most recent call last):
  File "F:\STABLE_DIFF\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "F:\STABLE_DIFF\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    compiled = compile(text, path, 'exec')
  File "F:\STABLE_DIFF\stable-diffusion-webui\scripts\vid2vid.py", line 72
    <title>Stable-Diffusion-Video2Video/vid2vid.py at main · Leonm99/Stable-Diffusion-Video2Video</title>
                                                           ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by Leonm99** [comment]
Sorry i dont know what your issue is, its working fine on my end.
"<title>Stable-Diffusion-Video2Video/vid2vid.py at main · Leonm99/Stable-Diffusion-Video2Video</title>" 
⬆️this isnt even part of my script. try redownloading the python file and place it in the scripts folder again. make sure you have ffmpeg as well.
