### ISSUE TITLE
Error loading script: vid2vid.py

### ISSUE THREAD

**Issue by DennisReactive** [Leonm99/Stable-Diffusion-Video2Video#8]
from cmd:
Error loading script: vid2vid.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    compiled = compile(text, path, 'exec')
  File "D:\stable-diffusion-webui\scripts\vid2vid.py", line 64
    <title>Stable-Diffusion-Video2Video/vid2vid.py at main · Leonm99/Stable-Diffusion-Video2Video</title>
                                                           ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by Leonm99** [comment]
check this out: https://github.com/Filarius/stable-diffusion-webui/blob/master/scripts/vid2vid.py

im discontinuing my version of vid2vid since this person seems to have done it better/improved on it. hope it will work well for you!
